[build]
builder = "nixpacks"

[build.nixpacks]
aptPackages = ["openssl"]

[deploy]
startCommand = "npm run build && npx prisma generate && npx prisma migrate deploy && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
