[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npx prisma generate && npx prisma migrate deploy && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_VERSION = "20"
