[build]
builder = "nixpacks"

[build.nixpacks]
aptPackages = ["openssl"]

[deploy]
startCommand = "npx prisma migrate deploy && npx prisma generate && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[variables]
NODE_ENV = "production"
